import '../../core/local_db/powersync.dart'; // exposes `db`
import '../../models/produce_listing.dart';

class ProduceListingService {
  /// Publishes a new listing. [listingId] is generated by the caller so
  /// the listing's photo can be uploaded under a path keyed by it before
  /// the row exists.
  ///
  /// `status_text` is the locally-synced mirror of the `status` enum
  /// (PowerSync can't carry enums). Setting it here is what makes the
  /// row display correctly offline; on upload, Postgres ignores the value
  /// — `status` takes its 'active' default and the
  /// `trg_produce_listing_powersync_mirrors` BEFORE INSERT trigger
  /// recomputes `status_text` from it.
  Future<void> createListing({
    required String listingId,
    required String farmerProfileId,
    required String cropId,
    required double pricePerKg,
    required double quantityKg,
    String? description,
    String? imageUrl,
    DateTime? harvestedOn,
  }) async {
    await db.execute(
      '''
      INSERT INTO produce_listing (
        id, farmer_profile_id, crop_id, price_per_kg, available_quantity_kg,
        status_text, description, image_url, harvested_on, published_at
      ) VALUES (?, ?, ?, ?, ?, 'active', ?, ?, ?, ?)
      ''',
      [
        listingId,
        farmerProfileId,
        cropId,
        pricePerKg,
        quantityKg,
        description,
        imageUrl,
        harvestedOn?.toIso8601String().split('T').first,
        DateTime.now().toIso8601String(),
      ],
    );
  }

  /// Every listing this farmer has posted, newest first, with the
  /// description fallback chain (listing -> farmer_crop) already
  /// applied — the same coalesce the marketplace_listing_read view does
  /// server-side, done here against the local mirror. The image columns
  /// are left un-coalesced (see `ProduceListing.displayImage`) since
  /// each tier lives in a different storage bucket.
  Stream<List<ProduceListing>> watchOwnListings(String farmerProfileId) {
    return db
        .watch(
          '''
      SELECT
        pl.id,
        pl.crop_id,
        c.name                                 AS crop_name,
        c.category                             AS crop_category,
        pl.price_per_kg,
        pl.available_quantity_kg,
        pl.status_text,
        COALESCE(pl.description, fc.description) AS description,
        pl.image_url                           AS listing_image_url,
        fc.image_url                           AS farmer_crop_image_url,
        c.fallback_image_url                   AS crop_fallback_image_url,
        pl.harvested_on
      FROM produce_listing pl
      JOIN crop c ON c.id = pl.crop_id
      LEFT JOIN farmer_crop fc
        ON fc.farmer_profile_id = pl.farmer_profile_id
       AND fc.crop_id = pl.crop_id
      WHERE pl.farmer_profile_id = ?
      ORDER BY pl.published_at DESC
      ''',
          parameters: [farmerProfileId],
        )
        .map((rows) => rows.map(ProduceListing.fromMap).toList());
  }
}
